### ISSUE TITLE
Add shortest path algo

### ISSUE THREAD

**Issue by MrPowers** [thieman/py-dag#29] opened 2020-06-30 03:43 UTC
Really enjoying playing with this library to learn some Python.

Here's a graph that's used a lot in the tests:

```python
dag.from_dict({'a': ['b', 'c'],
               'b': ['d'],
               'c': ['d'],
               'd': []})
```

For this graph the shortest path from a to d is a => b = d

Here's how this algo can be implemented:

```python
def iter_flatten(iterable):
  it = iter(iterable)
  for e in it:
    if isinstance(e, (list, tuple)):
      for f in iter_flatten(e):
        yield f
    else:
      yield e

def shortest_path(self, start, end, graph=None):
    if graph is None:
        graph = self.graph
    dist = {start: [start]}
    q = deque([start])
    while len(q):
        at = q.popleft()
        for next in graph[at]:
            if next not in dist:
                dist[next] = [dist[at], next]
                q.append(next)
    a = dist.get(end)
    return [i for i in iter_flatten(a)]
```

The `iter_flatten` is a hack and could probably be improved a bunch, but it works!

Let me know if you'd be open to adding this and I can send a pull request with some tests.

**Comment by thieman** [comment] 2020-06-30 21:16
Thanks, Matt. I'm happy you're having a fun time. 😄 

I currently don't think we should open up the library to including graph algorithms like this one.

1. The maintenance time I'm able (or willing) to put into this library is quite small. Adding algorithms seems like an unbounded feature set that could massively increase the scope of the project.

2. Graph algorithms strike me as pretty performance-sensitive. Not only would we need to consider bug fixes, we'd need to consider speed and memory implications of any changes we make to any of the algorithms. To do this properly, we'd want performance regression tests. We don't have CI working at all on this repo right now, so that's another thing to do.

The topo sort currently implemented is an exception to this general stance largely because it's a basic traversal, and you often need _some_ sort of way to meaningfully traverse the graph to do anything meaningful with it at all. It's possible even with that reasoning it's a bit hypocritical, but since it's already in the library I see no reason to remove it.

I'm going to go ahead and close this feature request. If you'd still like to go with the idea, you're more than welcome to do so on your fork (and I might even use it some day!). The library is MIT licensed which I hope meets any of your needs.

**Closed as completed by thieman** 2020-06-30 21:16 UTC

**Comment by MrPowers** [comment] 2020-06-30 21:22
Thanks for the detailed response.  I am going to try to create a purely functional implementation of DAGs in a separate library.  I'll let you know when it's done in case you want to use it ;)
